name: Deep Learning AIO

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  run-docker-container:
    runs-on: self-hosted  # Ensure your runner is self-hosted with GPU support

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Pull the Docker image
      - name: Pull Docker Image
        run: |
          docker pull harshshinde/deep-learning-aio:gpu

      # Step 3: Run the Docker container with GPU
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 8888:8888 \
            --gpus all \
            --restart unless-stopped \
            harshshinde/deep-learning-aio:gpu

      # Step 4: Verify the container is running (optional)
      - name: Verify Container Status
        run: |
          docker ps -a
